import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import CategoryAccordion from "@/components/Accordion/CategoryAccordion";
import VideoPlaylist from "@/components/VideoPlaylist/VideoPlaylist";
import { CategoryProvider } from "@/context/CategoryContext";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Career resource hub</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <h1>Career Resource Hub</h1>
        <CategoryProvider>
          <div className={styles.subTitle}>Articles </div>
          <CategoryAccordion />

          <div className={styles.subTitle}>Videos</div>
          <VideoPlaylist category="marketing" />
        </CategoryProvider>
      </main>
    </>
  );
}
